language: elixir
elixir:
  - 1.3.3
  - 1.3.4
  - 1.4.0-rc.0
  - 1.4.0-rc.1
  - 1.4.0
  - 1.4.1
  - 1.4.2
  - 1.4.4
otp_release:
  - 19.3
  - 19.2
  - 19.1
  - 19.0
  - 18.1
  - 18.0
matrix:
  include:
    - otp_release: 20.0-rc1
      elixir: 1.4.4
addons:
  artifacts:
    debug: true
    paths:
      - $(ls plts/*.plt)
    working_dir: plts
    target_paths:
      - travis_elixir_plts
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - git clone https://github.com/jeremyjh/dialyxir.git
  - cd dialyxir
  - MIX_ENV=prod mix do compile, archive.build
  - MIX_ENV=prod mix archive.install --force
  - cd ..
script:
  - MIX_ENV=test mix dialyzer --plt
